
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action FileAction;
	private global::Gtk.VBox vbox1;
	private global::Gtk.Table table19;
	private global::RippleClientGtk.CurrencyWidget currencywidget10;
	private global::RippleClientGtk.CurrencyWidget currencywidget9;
	private global::Gtk.HSeparator hseparator19;
	private global::Gtk.MenuBar menubar1;
	private global::RippleClientGtk.ReceiveWidget receivewidget2;
	private global::Gtk.VSeparator vseparator1;
	private global::Gtk.Notebook notebook1;
	private global::RippleClientGtk.Wallet wallet1;
	private global::Gtk.Label label15;
	private global::RippleClientGtk.NetworkSettings networksettings1;
	private global::Gtk.Label label25;
	private global::RippleClientGtk.BalanceTab balancetab1;
	private global::Gtk.Label label35;
	private global::RippleClientGtk.SendRipple sendripple2;
	private global::Gtk.Label label40;
	private global::RippleClientGtk.SendIOU sendiou1;
	private global::Gtk.Label label48;
	private global::RippleClientGtk.SendIce sendice1;
	private global::Gtk.Label label57;
	private global::RippleClientGtk.SendAndConvert sendandconvert1;
	private global::Gtk.Label label65;
	private global::RippleClientGtk.TrustSetter trustsetter1;
	private global::Gtk.Label label70;
	private global::RippleClientGtk.AccountLines accountlines1;
	private global::Gtk.Label label72;
	private global::RippleClientGtk.ServerInfo serverinfo1;
	private global::Gtk.Label label75;
	private global::RippleClientGtk.Console console1;
	private global::Gtk.Label label77;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("_File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_File");
		w1.Add (this.FileAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Ripple Client Gtk");
		this.Icon = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./rip.png"));
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		this.BorderWidth = ((uint)(3));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.table19 = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
		this.table19.Name = "table19";
		this.table19.RowSpacing = ((uint)(6));
		this.table19.ColumnSpacing = ((uint)(6));
		// Container child table19.Gtk.Table+TableChild
		this.currencywidget10 = new global::RippleClientGtk.CurrencyWidget ();
		this.currencywidget10.CanFocus = true;
		this.currencywidget10.Events = ((global::Gdk.EventMask)(256));
		this.currencywidget10.Name = "currencywidget10";
		this.table19.Add (this.currencywidget10);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table19 [this.currencywidget10]));
		w2.LeftAttach = ((uint)(2));
		w2.RightAttach = ((uint)(3));
		w2.XOptions = ((global::Gtk.AttachOptions)(4));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table19.Gtk.Table+TableChild
		this.currencywidget9 = new global::RippleClientGtk.CurrencyWidget ();
		this.currencywidget9.Events = ((global::Gdk.EventMask)(256));
		this.currencywidget9.Name = "currencywidget9";
		this.table19.Add (this.currencywidget9);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table19 [this.currencywidget9]));
		w3.TopAttach = ((uint)(1));
		w3.BottomAttach = ((uint)(2));
		w3.LeftAttach = ((uint)(2));
		w3.RightAttach = ((uint)(3));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table19.Gtk.Table+TableChild
		this.hseparator19 = new global::Gtk.HSeparator ();
		this.hseparator19.Name = "hseparator19";
		this.table19.Add (this.hseparator19);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table19 [this.hseparator19]));
		w4.TopAttach = ((uint)(2));
		w4.BottomAttach = ((uint)(3));
		w4.RightAttach = ((uint)(3));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table19.Gtk.Table+TableChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'/></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.table19.Add (this.menubar1);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table19 [this.menubar1]));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table19.Gtk.Table+TableChild
		this.receivewidget2 = new global::RippleClientGtk.ReceiveWidget ();
		this.receivewidget2.Events = ((global::Gdk.EventMask)(256));
		this.receivewidget2.Name = "receivewidget2";
		this.table19.Add (this.receivewidget2);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table19 [this.receivewidget2]));
		w6.TopAttach = ((uint)(1));
		w6.BottomAttach = ((uint)(2));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table19.Gtk.Table+TableChild
		this.vseparator1 = new global::Gtk.VSeparator ();
		this.vseparator1.Name = "vseparator1";
		this.table19.Add (this.vseparator1);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table19 [this.vseparator1]));
		w7.BottomAttach = ((uint)(3));
		w7.LeftAttach = ((uint)(1));
		w7.RightAttach = ((uint)(2));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox1.Add (this.table19);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.table19]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.notebook1 = new global::Gtk.Notebook ();
		this.notebook1.CanFocus = true;
		this.notebook1.Name = "notebook1";
		this.notebook1.CurrentPage = 1;
		this.notebook1.Scrollable = true;
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.wallet1 = new global::RippleClientGtk.Wallet ();
		this.wallet1.Events = ((global::Gdk.EventMask)(256));
		this.wallet1.Name = "wallet1";
		this.notebook1.Add (this.wallet1);
		// Notebook tab
		this.label15 = new global::Gtk.Label ();
		this.label15.Name = "label15";
		this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("Wallet");
		this.notebook1.SetTabLabel (this.wallet1, this.label15);
		this.label15.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.networksettings1 = new global::RippleClientGtk.NetworkSettings ();
		this.networksettings1.Events = ((global::Gdk.EventMask)(256));
		this.networksettings1.Name = "networksettings1";
		this.notebook1.Add (this.networksettings1);
		global::Gtk.Notebook.NotebookChild w10 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.networksettings1]));
		w10.Position = 1;
		// Notebook tab
		this.label25 = new global::Gtk.Label ();
		this.label25.Name = "label25";
		this.label25.LabelProp = global::Mono.Unix.Catalog.GetString ("Network");
		this.notebook1.SetTabLabel (this.networksettings1, this.label25);
		this.label25.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.balancetab1 = new global::RippleClientGtk.BalanceTab ();
		this.balancetab1.Events = ((global::Gdk.EventMask)(256));
		this.balancetab1.Name = "balancetab1";
		this.notebook1.Add (this.balancetab1);
		global::Gtk.Notebook.NotebookChild w11 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.balancetab1]));
		w11.Position = 2;
		// Notebook tab
		this.label35 = new global::Gtk.Label ();
		this.label35.Name = "label35";
		this.label35.LabelProp = global::Mono.Unix.Catalog.GetString ("Balances");
		this.notebook1.SetTabLabel (this.balancetab1, this.label35);
		this.label35.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.sendripple2 = new global::RippleClientGtk.SendRipple ();
		this.sendripple2.Events = ((global::Gdk.EventMask)(256));
		this.sendripple2.Name = "sendripple2";
		this.notebook1.Add (this.sendripple2);
		global::Gtk.Notebook.NotebookChild w12 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.sendripple2]));
		w12.Position = 3;
		// Notebook tab
		this.label40 = new global::Gtk.Label ();
		this.label40.Name = "label40";
		this.label40.LabelProp = global::Mono.Unix.Catalog.GetString ("Send Xrp");
		this.notebook1.SetTabLabel (this.sendripple2, this.label40);
		this.label40.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.sendiou1 = new global::RippleClientGtk.SendIOU ();
		this.sendiou1.Events = ((global::Gdk.EventMask)(256));
		this.sendiou1.Name = "sendiou1";
		this.notebook1.Add (this.sendiou1);
		global::Gtk.Notebook.NotebookChild w13 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.sendiou1]));
		w13.Position = 4;
		// Notebook tab
		this.label48 = new global::Gtk.Label ();
		this.label48.Name = "label48";
		this.label48.LabelProp = global::Mono.Unix.Catalog.GetString ("Send IOU");
		this.notebook1.SetTabLabel (this.sendiou1, this.label48);
		this.label48.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.sendice1 = new global::RippleClientGtk.SendIce ();
		this.sendice1.Events = ((global::Gdk.EventMask)(256));
		this.sendice1.Name = "sendice1";
		this.notebook1.Add (this.sendice1);
		global::Gtk.Notebook.NotebookChild w14 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.sendice1]));
		w14.Position = 5;
		// Notebook tab
		this.label57 = new global::Gtk.Label ();
		this.label57.Name = "label57";
		this.label57.LabelProp = global::Mono.Unix.Catalog.GetString ("Send ICE");
		this.notebook1.SetTabLabel (this.sendice1, this.label57);
		this.label57.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.sendandconvert1 = new global::RippleClientGtk.SendAndConvert ();
		this.sendandconvert1.Events = ((global::Gdk.EventMask)(256));
		this.sendandconvert1.Name = "sendandconvert1";
		this.notebook1.Add (this.sendandconvert1);
		global::Gtk.Notebook.NotebookChild w15 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.sendandconvert1]));
		w15.Position = 6;
		// Notebook tab
		this.label65 = new global::Gtk.Label ();
		this.label65.Name = "label65";
		this.label65.LabelProp = global::Mono.Unix.Catalog.GetString ("Send And Convert");
		this.notebook1.SetTabLabel (this.sendandconvert1, this.label65);
		this.label65.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.trustsetter1 = new global::RippleClientGtk.TrustSetter ();
		this.trustsetter1.Events = ((global::Gdk.EventMask)(256));
		this.trustsetter1.Name = "trustsetter1";
		this.notebook1.Add (this.trustsetter1);
		global::Gtk.Notebook.NotebookChild w16 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.trustsetter1]));
		w16.Position = 7;
		// Notebook tab
		this.label70 = new global::Gtk.Label ();
		this.label70.Name = "label70";
		this.label70.LabelProp = global::Mono.Unix.Catalog.GetString ("Set Trust");
		this.notebook1.SetTabLabel (this.trustsetter1, this.label70);
		this.label70.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.accountlines1 = new global::RippleClientGtk.AccountLines ();
		this.accountlines1.Events = ((global::Gdk.EventMask)(256));
		this.accountlines1.Name = "accountlines1";
		this.notebook1.Add (this.accountlines1);
		global::Gtk.Notebook.NotebookChild w17 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.accountlines1]));
		w17.Position = 8;
		// Notebook tab
		this.label72 = new global::Gtk.Label ();
		this.label72.Name = "label72";
		this.label72.LabelProp = global::Mono.Unix.Catalog.GetString ("Lines");
		this.notebook1.SetTabLabel (this.accountlines1, this.label72);
		this.label72.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.serverinfo1 = new global::RippleClientGtk.ServerInfo ();
		this.serverinfo1.Events = ((global::Gdk.EventMask)(256));
		this.serverinfo1.Name = "serverinfo1";
		this.notebook1.Add (this.serverinfo1);
		global::Gtk.Notebook.NotebookChild w18 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.serverinfo1]));
		w18.Position = 9;
		// Notebook tab
		this.label75 = new global::Gtk.Label ();
		this.label75.Name = "label75";
		this.label75.LabelProp = global::Mono.Unix.Catalog.GetString ("Server Info");
		this.notebook1.SetTabLabel (this.serverinfo1, this.label75);
		this.label75.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.console1 = new global::RippleClientGtk.Console ();
		this.console1.Events = ((global::Gdk.EventMask)(256));
		this.console1.Name = "console1";
		this.notebook1.Add (this.console1);
		global::Gtk.Notebook.NotebookChild w19 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.console1]));
		w19.Position = 10;
		// Notebook tab
		this.label77 = new global::Gtk.Label ();
		this.label77.Name = "label77";
		this.label77.LabelProp = global::Mono.Unix.Catalog.GetString ("Console");
		this.notebook1.SetTabLabel (this.console1, this.label77);
		this.label77.ShowAll ();
		this.vbox1.Add (this.notebook1);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.notebook1]));
		w20.Position = 1;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 867;
		this.DefaultHeight = 435;
		this.Hide ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
