
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.HBox hbox10;
	private global::Gtk.Label label8;
	private global::Gtk.Label balanceLabel;
	private global::RippleClientGtk.ReceiveWidget receivewidget2;
	private global::Gtk.Notebook notebook1;
	private global::RippleClientGtk.Wallet wallet1;
	private global::Gtk.Label label3;
	private global::RippleClientGtk.NetworkSettings networksettings1;
	private global::Gtk.Label label22;
	private global::RippleClientGtk.SendRipple sendripple2;
	private global::Gtk.Label label2;
	private global::RippleClientGtk.SendIOU sendiou1;
	private global::Gtk.Label label31;
	private global::RippleClientGtk.SendAndConvert sendandconvert1;
	private global::Gtk.Label label41;
	private global::RippleClientGtk.Console console1;
	private global::Gtk.Label label43;
	private global::RippleClientGtk.AccountLines accountlines1;
	private global::Gtk.Label label9;
	private global::RippleClientGtk.ServerInfo serverinfo1;
	private global::Gtk.Label label10;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Ripple Client Gtk");
		this.Icon = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./rip.png"));
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		this.BorderWidth = ((uint)(3));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox10 = new global::Gtk.HBox ();
		this.hbox10.Name = "hbox10";
		this.hbox10.Spacing = 6;
		// Container child hbox10.Gtk.Box+BoxChild
		this.label8 = new global::Gtk.Label ();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Balance</b>");
		this.label8.UseMarkup = true;
		this.hbox10.Add (this.label8);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.label8]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.balanceLabel = new global::Gtk.Label ();
		this.balanceLabel.WidthRequest = 174;
		this.balanceLabel.Name = "balanceLabel";
		this.balanceLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("  --  unsynced --  ");
		this.balanceLabel.Selectable = true;
		this.hbox10.Add (this.balanceLabel);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.balanceLabel]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.receivewidget2 = new global::RippleClientGtk.ReceiveWidget ();
		this.receivewidget2.Events = ((global::Gdk.EventMask)(256));
		this.receivewidget2.Name = "receivewidget2";
		this.hbox10.Add (this.receivewidget2);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.receivewidget2]));
		w3.Position = 2;
		this.vbox1.Add (this.hbox10);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox10]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.notebook1 = new global::Gtk.Notebook ();
		this.notebook1.CanFocus = true;
		this.notebook1.Name = "notebook1";
		this.notebook1.CurrentPage = 2;
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.wallet1 = new global::RippleClientGtk.Wallet ();
		this.wallet1.Events = ((global::Gdk.EventMask)(256));
		this.wallet1.Name = "wallet1";
		this.notebook1.Add (this.wallet1);
		// Notebook tab
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Wallet");
		this.notebook1.SetTabLabel (this.wallet1, this.label3);
		this.label3.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.networksettings1 = new global::RippleClientGtk.NetworkSettings ();
		this.networksettings1.Events = ((global::Gdk.EventMask)(256));
		this.networksettings1.Name = "networksettings1";
		this.notebook1.Add (this.networksettings1);
		global::Gtk.Notebook.NotebookChild w6 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.networksettings1]));
		w6.Position = 1;
		// Notebook tab
		this.label22 = new global::Gtk.Label ();
		this.label22.Name = "label22";
		this.label22.LabelProp = global::Mono.Unix.Catalog.GetString ("Network");
		this.notebook1.SetTabLabel (this.networksettings1, this.label22);
		this.label22.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.sendripple2 = new global::RippleClientGtk.SendRipple ();
		this.sendripple2.Events = ((global::Gdk.EventMask)(256));
		this.sendripple2.Name = "sendripple2";
		this.notebook1.Add (this.sendripple2);
		global::Gtk.Notebook.NotebookChild w7 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.sendripple2]));
		w7.Position = 2;
		// Notebook tab
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Send Xrp");
		this.notebook1.SetTabLabel (this.sendripple2, this.label2);
		this.label2.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.sendiou1 = new global::RippleClientGtk.SendIOU ();
		this.sendiou1.Events = ((global::Gdk.EventMask)(256));
		this.sendiou1.Name = "sendiou1";
		this.notebook1.Add (this.sendiou1);
		global::Gtk.Notebook.NotebookChild w8 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.sendiou1]));
		w8.Position = 3;
		// Notebook tab
		this.label31 = new global::Gtk.Label ();
		this.label31.Name = "label31";
		this.label31.LabelProp = global::Mono.Unix.Catalog.GetString ("Send IOU");
		this.notebook1.SetTabLabel (this.sendiou1, this.label31);
		this.label31.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.sendandconvert1 = new global::RippleClientGtk.SendAndConvert ();
		this.sendandconvert1.Events = ((global::Gdk.EventMask)(256));
		this.sendandconvert1.Name = "sendandconvert1";
		this.notebook1.Add (this.sendandconvert1);
		global::Gtk.Notebook.NotebookChild w9 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.sendandconvert1]));
		w9.Position = 4;
		// Notebook tab
		this.label41 = new global::Gtk.Label ();
		this.label41.Name = "label41";
		this.label41.LabelProp = global::Mono.Unix.Catalog.GetString ("Send And Convert");
		this.notebook1.SetTabLabel (this.sendandconvert1, this.label41);
		this.label41.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.console1 = new global::RippleClientGtk.Console ();
		this.console1.Events = ((global::Gdk.EventMask)(256));
		this.console1.Name = "console1";
		this.notebook1.Add (this.console1);
		global::Gtk.Notebook.NotebookChild w10 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.console1]));
		w10.Position = 5;
		// Notebook tab
		this.label43 = new global::Gtk.Label ();
		this.label43.Name = "label43";
		this.label43.LabelProp = global::Mono.Unix.Catalog.GetString ("Console");
		this.notebook1.SetTabLabel (this.console1, this.label43);
		this.label43.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.accountlines1 = new global::RippleClientGtk.AccountLines ();
		this.accountlines1.Events = ((global::Gdk.EventMask)(256));
		this.accountlines1.Name = "accountlines1";
		this.notebook1.Add (this.accountlines1);
		global::Gtk.Notebook.NotebookChild w11 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.accountlines1]));
		w11.Position = 6;
		// Notebook tab
		this.label9 = new global::Gtk.Label ();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Lines");
		this.notebook1.SetTabLabel (this.accountlines1, this.label9);
		this.label9.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.serverinfo1 = new global::RippleClientGtk.ServerInfo ();
		this.serverinfo1.Events = ((global::Gdk.EventMask)(256));
		this.serverinfo1.Name = "serverinfo1";
		this.notebook1.Add (this.serverinfo1);
		global::Gtk.Notebook.NotebookChild w12 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.serverinfo1]));
		w12.Position = 7;
		// Notebook tab
		this.label10 = new global::Gtk.Label ();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Server Info");
		this.notebook1.SetTabLabel (this.serverinfo1, this.label10);
		this.label10.ShowAll ();
		this.vbox1.Add (this.notebook1);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.notebook1]));
		w13.Position = 1;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 766;
		this.DefaultHeight = 353;
		this.Hide ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
