
// This file has been generated by the GUI designer. Do not modify.
namespace RippleClientGtk
{
	public partial class SendAndConvert
	{
		private global::Gtk.VBox vbox4;
		private global::Gtk.Label label18;
		private global::Gtk.HSeparator hseparator8;
		private global::Gtk.Table table5;
		private global::Gtk.Entry destinationentry;
		private global::Gtk.HBox hbox5;
		private global::Gtk.ComboBoxEntry comboboxentry;
		private global::Gtk.Label label14;
		private global::Gtk.Label balancelabel;
		private global::Gtk.HBox hbox6;
		private global::Gtk.Entry sendmaxentry;
		private global::Gtk.Label label20;
		private global::Gtk.HBox hbox7;
		private global::Gtk.Entry receiveamountentry;
		private global::Gtk.ComboBoxEntry comboboxentry2;
		private global::Gtk.Entry issuerentry;
		private global::Gtk.Label label12;
		private global::Gtk.Label label13;
		private global::Gtk.Label label16;
		private global::Gtk.Label label17;
		private global::Gtk.Label label19;
		private global::Gtk.Button sendbutton;
		private global::Gtk.HSeparator hseparator9;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget RippleClientGtk.SendAndConvert
			global::Stetic.BinContainer.Attach (this);
			this.Name = "RippleClientGtk.SendAndConvert";
			// Container child RippleClientGtk.SendAndConvert.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			this.vbox4.BorderWidth = ((uint)(5));
			// Container child vbox4.Gtk.Box+BoxChild
			this.label18 = new global::Gtk.Label ();
			this.label18.Name = "label18";
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString ("<big><b><u>Send And Convert</u></b></big>");
			this.label18.UseMarkup = true;
			this.vbox4.Add (this.label18);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.label18]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hseparator8 = new global::Gtk.HSeparator ();
			this.hseparator8.Name = "hseparator8";
			this.vbox4.Add (this.hseparator8);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hseparator8]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.table5 = new global::Gtk.Table (((uint)(5)), ((uint)(2)), false);
			this.table5.Name = "table5";
			this.table5.RowSpacing = ((uint)(6));
			this.table5.ColumnSpacing = ((uint)(6));
			// Container child table5.Gtk.Table+TableChild
			this.destinationentry = new global::Gtk.Entry ();
			this.destinationentry.CanFocus = true;
			this.destinationentry.Name = "destinationentry";
			this.destinationentry.IsEditable = true;
			this.destinationentry.InvisibleChar = '●';
			this.table5.Add (this.destinationentry);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table5 [this.destinationentry]));
			w3.TopAttach = ((uint)(2));
			w3.BottomAttach = ((uint)(3));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.comboboxentry = global::Gtk.ComboBoxEntry.NewText ();
			this.comboboxentry.WidthRequest = 70;
			this.comboboxentry.Name = "comboboxentry";
			this.hbox5.Add (this.comboboxentry);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.comboboxentry]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label14 = new global::Gtk.Label ();
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Balance</b>");
			this.label14.UseMarkup = true;
			this.hbox5.Add (this.label14);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label14]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.balancelabel = new global::Gtk.Label ();
			this.balancelabel.Name = "balancelabel";
			this.balancelabel.LabelProp = global::Mono.Unix.Catalog.GetString ("   --   unsynced   --   ");
			this.hbox5.Add (this.balancelabel);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.balancelabel]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			this.table5.Add (this.hbox5);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table5 [this.hbox5]));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.sendmaxentry = new global::Gtk.Entry ();
			this.sendmaxentry.CanFocus = true;
			this.sendmaxentry.Name = "sendmaxentry";
			this.sendmaxentry.IsEditable = true;
			this.sendmaxentry.InvisibleChar = '●';
			this.hbox6.Add (this.sendmaxentry);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.sendmaxentry]));
			w8.Position = 0;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label20 = new global::Gtk.Label ();
			this.label20.WidthRequest = 40;
			this.label20.Name = "label20";
			this.label20.LabelProp = global::Mono.Unix.Catalog.GetString ("GWC");
			this.hbox6.Add (this.label20);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label20]));
			w9.PackType = ((global::Gtk.PackType)(1));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			this.table5.Add (this.hbox6);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table5 [this.hbox6]));
			w10.TopAttach = ((uint)(3));
			w10.BottomAttach = ((uint)(4));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.receiveamountentry = new global::Gtk.Entry ();
			this.receiveamountentry.CanFocus = true;
			this.receiveamountentry.Name = "receiveamountentry";
			this.receiveamountentry.IsEditable = true;
			this.receiveamountentry.InvisibleChar = '●';
			this.hbox7.Add (this.receiveamountentry);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.receiveamountentry]));
			w11.Position = 0;
			// Container child hbox7.Gtk.Box+BoxChild
			this.comboboxentry2 = global::Gtk.ComboBoxEntry.NewText ();
			this.comboboxentry2.AppendText (global::Mono.Unix.Catalog.GetString ("USD"));
			this.comboboxentry2.AppendText (global::Mono.Unix.Catalog.GetString ("CAD"));
			this.comboboxentry2.AppendText (global::Mono.Unix.Catalog.GetString ("GWC"));
			this.comboboxentry2.WidthRequest = 70;
			this.comboboxentry2.Name = "comboboxentry2";
			this.comboboxentry2.Active = 0;
			this.hbox7.Add (this.comboboxentry2);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.comboboxentry2]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			this.table5.Add (this.hbox7);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table5 [this.hbox7]));
			w13.TopAttach = ((uint)(4));
			w13.BottomAttach = ((uint)(5));
			w13.LeftAttach = ((uint)(1));
			w13.RightAttach = ((uint)(2));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.issuerentry = new global::Gtk.Entry ();
			this.issuerentry.CanFocus = true;
			this.issuerentry.Name = "issuerentry";
			this.issuerentry.IsEditable = true;
			this.issuerentry.InvisibleChar = '●';
			this.table5.Add (this.issuerentry);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table5 [this.issuerentry]));
			w14.TopAttach = ((uint)(1));
			w14.BottomAttach = ((uint)(2));
			w14.LeftAttach = ((uint)(1));
			w14.RightAttach = ((uint)(2));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.Xalign = 0F;
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Send Max</b>");
			this.label12.UseMarkup = true;
			this.table5.Add (this.label12);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table5 [this.label12]));
			w15.TopAttach = ((uint)(3));
			w15.BottomAttach = ((uint)(4));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.label13 = new global::Gtk.Label ();
			this.label13.Name = "label13";
			this.label13.Xalign = 0F;
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Currency</b>");
			this.label13.UseMarkup = true;
			this.table5.Add (this.label13);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table5 [this.label13]));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.label16 = new global::Gtk.Label ();
			this.label16.Name = "label16";
			this.label16.Xalign = 0F;
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>They Receive</b>");
			this.label16.UseMarkup = true;
			this.table5.Add (this.label16);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table5 [this.label16]));
			w17.TopAttach = ((uint)(4));
			w17.BottomAttach = ((uint)(5));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.label17 = new global::Gtk.Label ();
			this.label17.Name = "label17";
			this.label17.Xalign = 0F;
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Issuer</b>");
			this.label17.UseMarkup = true;
			this.table5.Add (this.label17);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table5 [this.label17]));
			w18.TopAttach = ((uint)(1));
			w18.BottomAttach = ((uint)(2));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.label19 = new global::Gtk.Label ();
			this.label19.Name = "label19";
			this.label19.Xalign = 0F;
			this.label19.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Destination</b>");
			this.label19.UseMarkup = true;
			this.table5.Add (this.label19);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table5 [this.label19]));
			w19.TopAttach = ((uint)(2));
			w19.BottomAttach = ((uint)(3));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox4.Add (this.table5);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.table5]));
			w20.Position = 2;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.sendbutton = new global::Gtk.Button ();
			this.sendbutton.CanFocus = true;
			this.sendbutton.Name = "sendbutton";
			this.sendbutton.UseUnderline = true;
			this.sendbutton.Label = global::Mono.Unix.Catalog.GetString ("Send");
			this.vbox4.Add (this.sendbutton);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.sendbutton]));
			w21.PackType = ((global::Gtk.PackType)(1));
			w21.Position = 3;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hseparator9 = new global::Gtk.HSeparator ();
			this.hseparator9.Name = "hseparator9";
			this.vbox4.Add (this.hseparator9);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hseparator9]));
			w22.PackType = ((global::Gtk.PackType)(1));
			w22.Position = 4;
			w22.Expand = false;
			w22.Fill = false;
			this.Add (this.vbox4);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.comboboxentry.Changed += new global::System.EventHandler (this.OnComboboxentryChanged);
		}
	}
}
