
// This file has been generated by the GUI designer. Do not modify.
namespace RippleClientGtk
{
	public partial class Console
	{
		private global::Gtk.VBox vbox6;
		private global::Gtk.Label label26;
		private global::Gtk.HSeparator hseparator10;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TextView consoleView;
		private global::Gtk.HSeparator hseparator11;
		private global::Gtk.HBox hbox11;
		private global::Gtk.Entry consoleentry;
		private global::Gtk.Button sendbutton;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget RippleClientGtk.Console
			global::Stetic.BinContainer.Attach (this);
			this.Name = "RippleClientGtk.Console";
			// Container child RippleClientGtk.Console.Gtk.Container+ContainerChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.label26 = new global::Gtk.Label ();
			this.label26.Name = "label26";
			this.label26.LabelProp = global::Mono.Unix.Catalog.GetString ("<big><b><u>Console</u></b></big>");
			this.label26.UseMarkup = true;
			this.label26.Justify = ((global::Gtk.Justification)(2));
			this.vbox6.Add (this.label26);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.label26]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			w1.Padding = ((uint)(5));
			// Container child vbox6.Gtk.Box+BoxChild
			this.hseparator10 = new global::Gtk.HSeparator ();
			this.hseparator10.Name = "hseparator10";
			this.vbox6.Add (this.hseparator10);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hseparator10]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.consoleView = new global::Gtk.TextView ();
			this.consoleView.CanFocus = true;
			this.consoleView.Name = "consoleView";
			this.consoleView.Editable = false;
			this.consoleView.CursorVisible = false;
			this.consoleView.AcceptsTab = false;
			this.consoleView.WrapMode = ((global::Gtk.WrapMode)(2));
			this.GtkScrolledWindow.Add (this.consoleView);
			this.vbox6.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.GtkScrolledWindow]));
			w4.Position = 2;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hseparator11 = new global::Gtk.HSeparator ();
			this.hseparator11.Name = "hseparator11";
			this.vbox6.Add (this.hseparator11);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hseparator11]));
			w5.Position = 3;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox ();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.consoleentry = new global::Gtk.Entry ();
			this.consoleentry.CanFocus = true;
			this.consoleentry.Name = "consoleentry";
			this.consoleentry.IsEditable = true;
			this.consoleentry.InvisibleChar = '●';
			this.hbox11.Add (this.consoleentry);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.consoleentry]));
			w6.Position = 0;
			// Container child hbox11.Gtk.Box+BoxChild
			this.sendbutton = new global::Gtk.Button ();
			this.sendbutton.CanFocus = true;
			this.sendbutton.Name = "sendbutton";
			this.sendbutton.UseUnderline = true;
			this.sendbutton.Label = global::Mono.Unix.Catalog.GetString ("Send JSON");
			this.hbox11.Add (this.sendbutton);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.sendbutton]));
			w7.PackType = ((global::Gtk.PackType)(1));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			this.vbox6.Add (this.hbox11);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox11]));
			w8.Position = 4;
			w8.Expand = false;
			w8.Fill = false;
			this.Add (this.vbox6);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
