
// This file has been generated by the GUI designer. Do not modify.
namespace RippleClientGtk
{
	public partial class Console
	{
		private global::Gtk.VBox vbox6;
		private global::Gtk.Label label26;
		private global::Gtk.HSeparator hseparator10;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TextView consoleView;
		private global::Gtk.HSeparator hseparator11;
		private global::Gtk.HBox hbox11;
		private global::Gtk.Entry consoleentry;
		private global::Gtk.Button button979;
		private global::Gtk.Button button980;
		private global::Gtk.Button sendbutton;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget RippleClientGtk.Console
			global::Stetic.BinContainer.Attach (this);
			this.Name = "RippleClientGtk.Console";
			// Container child RippleClientGtk.Console.Gtk.Container+ContainerChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.label26 = new global::Gtk.Label ();
			this.label26.Name = "label26";
			this.label26.LabelProp = global::Mono.Unix.Catalog.GetString ("<big><b><u>Console</u></b></big>");
			this.label26.UseMarkup = true;
			this.label26.Justify = ((global::Gtk.Justification)(2));
			this.vbox6.Add (this.label26);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.label26]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			w1.Padding = ((uint)(5));
			// Container child vbox6.Gtk.Box+BoxChild
			this.hseparator10 = new global::Gtk.HSeparator ();
			this.hseparator10.Name = "hseparator10";
			this.vbox6.Add (this.hseparator10);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hseparator10]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.consoleView = new global::Gtk.TextView ();
			this.consoleView.CanFocus = true;
			this.consoleView.Name = "consoleView";
			this.consoleView.Editable = false;
			this.consoleView.CursorVisible = false;
			this.consoleView.AcceptsTab = false;
			this.consoleView.WrapMode = ((global::Gtk.WrapMode)(2));
			this.GtkScrolledWindow.Add (this.consoleView);
			this.vbox6.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.GtkScrolledWindow]));
			w4.Position = 2;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hseparator11 = new global::Gtk.HSeparator ();
			this.hseparator11.Name = "hseparator11";
			this.vbox6.Add (this.hseparator11);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hseparator11]));
			w5.Position = 3;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox ();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.consoleentry = new global::Gtk.Entry ();
			this.consoleentry.CanFocus = true;
			this.consoleentry.Name = "consoleentry";
			this.consoleentry.IsEditable = true;
			this.consoleentry.InvisibleChar = '●';
			this.hbox11.Add (this.consoleentry);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.consoleentry]));
			w6.Position = 0;
			// Container child hbox11.Gtk.Box+BoxChild
			this.button979 = new global::Gtk.Button ();
			this.button979.CanFocus = true;
			this.button979.Name = "button979";
			// Container child button979.Gtk.Container+ContainerChild
			global::Gtk.Alignment w7 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w8 = new global::Gtk.HBox ();
			w8.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w9 = new global::Gtk.Image ();
			w9.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_up", global::Gtk.IconSize.Menu);
			w8.Add (w9);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w11 = new global::Gtk.Label ();
			w11.LabelProp = "";
			w8.Add (w11);
			w7.Add (w8);
			this.button979.Add (w7);
			this.hbox11.Add (this.button979);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.button979]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.button980 = new global::Gtk.Button ();
			this.button980.CanFocus = true;
			this.button980.Name = "button980";
			// Container child button980.Gtk.Container+ContainerChild
			global::Gtk.Alignment w16 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w17 = new global::Gtk.HBox ();
			w17.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w18 = new global::Gtk.Image ();
			w18.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_down", global::Gtk.IconSize.Menu);
			w17.Add (w18);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w20 = new global::Gtk.Label ();
			w20.LabelProp = "";
			w17.Add (w20);
			w16.Add (w17);
			this.button980.Add (w16);
			this.hbox11.Add (this.button980);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.button980]));
			w24.Position = 2;
			w24.Expand = false;
			w24.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.sendbutton = new global::Gtk.Button ();
			this.sendbutton.CanFocus = true;
			this.sendbutton.Name = "sendbutton";
			this.sendbutton.UseUnderline = true;
			this.sendbutton.Label = global::Mono.Unix.Catalog.GetString ("Send JSON");
			this.hbox11.Add (this.sendbutton);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.sendbutton]));
			w25.PackType = ((global::Gtk.PackType)(1));
			w25.Position = 3;
			w25.Expand = false;
			w25.Fill = false;
			this.vbox6.Add (this.hbox11);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox11]));
			w26.Position = 4;
			w26.Expand = false;
			w26.Fill = false;
			this.Add (this.vbox6);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.button979.Clicked += new global::System.EventHandler (this.historyUp);
			this.button980.Clicked += new global::System.EventHandler (this.historyDown);
		}
	}
}
