
// This file has been generated by the GUI designer. Do not modify.
namespace RippleClientGtk
{
	public partial class BalanceTab
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.Label label1;
		private global::Gtk.HSeparator hseparator1;
		private global::Gtk.HBox hbox2;
		private global::RippleClientGtk.BalanceWidget balancewidget1;
		private global::Gtk.VBox vbox2;
		private global::RippleClientGtk.CurrencyWidget currencywidget1;
		private global::RippleClientGtk.CurrencyWidget currencywidget2;
		private global::RippleClientGtk.CurrencyWidget currencywidget3;
		private global::RippleClientGtk.CurrencyWidget currencywidget4;
		private global::RippleClientGtk.CurrencyWidget currencywidget5;
		private global::RippleClientGtk.CurrencyWidget currencywidget6;
		private global::RippleClientGtk.CurrencyWidget currencywidget7;
		private global::RippleClientGtk.CurrencyWidget currencywidget8;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget RippleClientGtk.BalanceTab
			global::Stetic.BinContainer.Attach (this);
			this.Name = "RippleClientGtk.BalanceTab";
			// Container child RippleClientGtk.BalanceTab.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("<big><b><u>Balances</u></b></big>");
			this.label1.UseMarkup = true;
			this.vbox1.Add (this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			w1.Padding = ((uint)(5));
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vbox1.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hseparator1]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Homogeneous = true;
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.balancewidget1 = new global::RippleClientGtk.BalanceWidget ();
			this.balancewidget1.Events = ((global::Gdk.EventMask)(256));
			this.balancewidget1.Name = "balancewidget1";
			this.hbox2.Add (this.balancewidget1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.balancewidget1]));
			w3.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.currencywidget1 = new global::RippleClientGtk.CurrencyWidget ();
			this.currencywidget1.Events = ((global::Gdk.EventMask)(256));
			this.currencywidget1.Name = "currencywidget1";
			this.vbox2.Add (this.currencywidget1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.currencywidget1]));
			w4.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.currencywidget2 = new global::RippleClientGtk.CurrencyWidget ();
			this.currencywidget2.Events = ((global::Gdk.EventMask)(256));
			this.currencywidget2.Name = "currencywidget2";
			this.vbox2.Add (this.currencywidget2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.currencywidget2]));
			w5.Position = 1;
			// Container child vbox2.Gtk.Box+BoxChild
			this.currencywidget3 = new global::RippleClientGtk.CurrencyWidget ();
			this.currencywidget3.Events = ((global::Gdk.EventMask)(256));
			this.currencywidget3.Name = "currencywidget3";
			this.vbox2.Add (this.currencywidget3);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.currencywidget3]));
			w6.Position = 2;
			// Container child vbox2.Gtk.Box+BoxChild
			this.currencywidget4 = new global::RippleClientGtk.CurrencyWidget ();
			this.currencywidget4.Events = ((global::Gdk.EventMask)(256));
			this.currencywidget4.Name = "currencywidget4";
			this.vbox2.Add (this.currencywidget4);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.currencywidget4]));
			w7.Position = 3;
			// Container child vbox2.Gtk.Box+BoxChild
			this.currencywidget5 = new global::RippleClientGtk.CurrencyWidget ();
			this.currencywidget5.Events = ((global::Gdk.EventMask)(256));
			this.currencywidget5.Name = "currencywidget5";
			this.vbox2.Add (this.currencywidget5);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.currencywidget5]));
			w8.Position = 4;
			// Container child vbox2.Gtk.Box+BoxChild
			this.currencywidget6 = new global::RippleClientGtk.CurrencyWidget ();
			this.currencywidget6.Events = ((global::Gdk.EventMask)(256));
			this.currencywidget6.Name = "currencywidget6";
			this.vbox2.Add (this.currencywidget6);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.currencywidget6]));
			w9.Position = 5;
			// Container child vbox2.Gtk.Box+BoxChild
			this.currencywidget7 = new global::RippleClientGtk.CurrencyWidget ();
			this.currencywidget7.Events = ((global::Gdk.EventMask)(256));
			this.currencywidget7.Name = "currencywidget7";
			this.vbox2.Add (this.currencywidget7);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.currencywidget7]));
			w10.Position = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.currencywidget8 = new global::RippleClientGtk.CurrencyWidget ();
			this.currencywidget8.Events = ((global::Gdk.EventMask)(256));
			this.currencywidget8.Name = "currencywidget8";
			this.vbox2.Add (this.currencywidget8);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.currencywidget8]));
			w11.Position = 7;
			this.hbox2.Add (this.vbox2);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox2]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w13.Position = 2;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
