
// This file has been generated by the GUI designer. Do not modify.
namespace RippleClientGtk
{
	public partial class SendRipple
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.Label label11;
		private global::Gtk.HSeparator hseparator4;
		private global::Gtk.Table table1;
		private global::Gtk.Label balanceLabel;
		private global::Gtk.ComboBoxEntry destinationcomboboxentry;
		private global::Gtk.HBox hbox1;
		private global::Gtk.ComboBoxEntry amountcomboboxentry;
		private global::Gtk.ComboBoxEntry unitsSelectBox;
		private global::Gtk.Label label12;
		private global::Gtk.Label label14;
		private global::Gtk.Label label16;
		private global::Gtk.Button sendXRPButton;
		private global::Gtk.HSeparator hseparator5;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget RippleClientGtk.SendRipple
			global::Stetic.BinContainer.Attach (this);
			this.Name = "RippleClientGtk.SendRipple";
			// Container child RippleClientGtk.SendRipple.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			this.vbox2.BorderWidth = ((uint)(5));
			// Container child vbox2.Gtk.Box+BoxChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("<big><b><u>Send Ripples</u></b></big>");
			this.label11.UseMarkup = true;
			this.vbox2.Add (this.label11);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label11]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hseparator4 = new global::Gtk.HSeparator ();
			this.hseparator4.Name = "hseparator4";
			this.vbox2.Add (this.hseparator4);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hseparator4]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.balanceLabel = new global::Gtk.Label ();
			this.balanceLabel.Name = "balanceLabel";
			this.balanceLabel.Xalign = 0F;
			this.balanceLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("   --   unsynced   --   ");
			this.balanceLabel.Selectable = true;
			this.table1.Add (this.balanceLabel);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.balanceLabel]));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.destinationcomboboxentry = global::Gtk.ComboBoxEntry.NewText ();
			this.destinationcomboboxentry.Name = "destinationcomboboxentry";
			this.table1.Add (this.destinationcomboboxentry);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.destinationcomboboxentry]));
			w4.TopAttach = ((uint)(2));
			w4.BottomAttach = ((uint)(3));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.amountcomboboxentry = global::Gtk.ComboBoxEntry.NewText ();
			this.amountcomboboxentry.Name = "amountcomboboxentry";
			this.hbox1.Add (this.amountcomboboxentry);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.amountcomboboxentry]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.unitsSelectBox = global::Gtk.ComboBoxEntry.NewText ();
			this.unitsSelectBox.AppendText (global::Mono.Unix.Catalog.GetString ("XRP"));
			this.unitsSelectBox.AppendText (global::Mono.Unix.Catalog.GetString ("drops"));
			this.unitsSelectBox.WidthRequest = 70;
			this.unitsSelectBox.Name = "unitsSelectBox";
			this.unitsSelectBox.Active = 1;
			this.hbox1.Add (this.unitsSelectBox);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.unitsSelectBox]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.table1.Add (this.hbox1);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.hbox1]));
			w7.TopAttach = ((uint)(1));
			w7.BottomAttach = ((uint)(2));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.Xalign = 0F;
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Amount</b>");
			this.label12.UseMarkup = true;
			this.table1.Add (this.label12);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1 [this.label12]));
			w8.TopAttach = ((uint)(1));
			w8.BottomAttach = ((uint)(2));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label14 = new global::Gtk.Label ();
			this.label14.Name = "label14";
			this.label14.Xalign = 0F;
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Balance</b>");
			this.label14.UseMarkup = true;
			this.table1.Add (this.label14);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.label14]));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label16 = new global::Gtk.Label ();
			this.label16.Name = "label16";
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Destination</b>");
			this.label16.UseMarkup = true;
			this.table1.Add (this.label16);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.label16]));
			w10.TopAttach = ((uint)(2));
			w10.BottomAttach = ((uint)(3));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox2.Add (this.table1);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.table1]));
			w11.Position = 2;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.sendXRPButton = new global::Gtk.Button ();
			this.sendXRPButton.CanFocus = true;
			this.sendXRPButton.Name = "sendXRPButton";
			this.sendXRPButton.UseUnderline = true;
			this.sendXRPButton.Label = global::Mono.Unix.Catalog.GetString ("Send");
			this.vbox2.Add (this.sendXRPButton);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.sendXRPButton]));
			w12.PackType = ((global::Gtk.PackType)(1));
			w12.Position = 3;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hseparator5 = new global::Gtk.HSeparator ();
			this.hseparator5.Name = "hseparator5";
			this.vbox2.Add (this.hseparator5);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hseparator5]));
			w13.PackType = ((global::Gtk.PackType)(1));
			w13.Position = 4;
			w13.Expand = false;
			w13.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.sendXRPButton.Clicked += new global::System.EventHandler (this.OnSendXRPButtonClicked);
		}
	}
}
