
// This file has been generated by the GUI designer. Do not modify.
namespace RippleClientGtk
{
	public partial class SplashWindow
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.Image image87;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget RippleClientGtk.SplashWindow
			this.Name = "RippleClientGtk.SplashWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("SplashWindow");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(4));
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.Resizable = false;
			this.AllowGrow = false;
			this.AcceptFocus = false;
			// Container child RippleClientGtk.SplashWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.image87 = new global::Gtk.Image ();
			this.image87.Name = "image87";
			this.image87.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./ice_splash.png"));
			this.vbox2.Add (this.image87);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.image87]));
			w1.Position = 0;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 374;
			this.DefaultHeight = 456;
			this.Show ();
		}
	}
}
